"""empty message

Revision ID: 7e3da98a51b9
Revises: 87a1022b2d05
Create Date: 2018-01-15 11:13:16.547270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e3da98a51b9'
down_revision = ''
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_industry_code'), 'stock_industry', ['code'], unique=False)
    op.create_index(op.f('ix_stock_industry_name'), 'stock_industry', ['name'], unique=False)
    op.create_index('ix_stock_industry_sourcelevel', 'stock_industry', ['source', 'level'], unique=False)
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('ix_stock_industry_sourcelevel', table_name='stock_industry')
    op.drop_index(op.f('ix_stock_industry_name'), table_name='stock_industry')
    op.drop_index(op.f('ix_stock_industry_code'), table_name='stock_industry')
    op.drop_table('stock_industry')
    # ### end Alembic commands ###
