#schedule jobs 
SUDDEN_QTY_INCRE = 'SUDDEN_QTY_INCRE'   #持有量激增
SUDDEN_QTY_REDUCE = 'SUDDEN_QTY_REDUCE' #持有量激减
INDUSTRY_STAT_TYPE = 'INDUSTRY_STAT_TYPE' #行业统计 
INDUSTRY_AMOUNT_INCRE = 'INDUSTRY_AMT_INC' #行业资金增量排名